import { useState } from "react";

function AddProperty({ user, refresh }) {
  const [title, setTitle] = useState("");
    const [price, setPrice] = useState("");
      const [location, setLocation] = useState("");
        const [contact, setContact] = useState("");
          const [image, setImage] = useState(null);
            const [loading, setLoading] = useState(false);
              const [msg, setMsg] = useState("");

                const handleUpload = async (e) => {
                    e.preventDefault();
                        if (!image) return alert("Please select an image");

                            setLoading(true);
                                setMsg("");

                                    try {
                                          // 1️⃣ Upload image to Cloudinary
                                                const data = new FormData();
                                                      data.append("file", image);
                                                            data.append("upload_preset", "homdira_uploads"); // set this in Cloudinary
                                                                  data.append("cloud_name", "dwwbua1jx");

                                                                        const cloudRes = await fetch("https://api.cloudinary.com/v1_1/dwwbua1jx/image/upload", {
                                                                                method: "POST",
                                                                                        body: data,
                                                                                              });

                                                                                                    const cloudData = await cloudRes.json();
                                                                                                          const imageUrl = cloudData.secure_url;

                                                                                                                // 2️⃣ Save property to backend
                                                                                                                      const res = await fetch("https://homdira-backend.onrender.com/api/properties", {
                                                                                                                              method: "POST",
                                                                                                                                      headers: {
                                                                                                                                                "Content-Type": "application/json",
                                                                                                                                                          Authorization: `Bearer ${localStorage.getItem("token")}`,
                                                                                                                                                                  },
                                                                                                                                                                          body: JSON.stringify({
                                                                                                                                                                                    title,
                                                                                                                                                                                              price,
                                                                                                                                                                                                        location,
                                                                                                                                                                                                                  contact,
                                                                                                                                                                                                                            imageUrl,
                                                                                                                                                                                                                                      landlord: user._id,
                                                                                                                                                                                                                                              }),
                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                          const backendData = await res.json();
                                                                                                                                                                                                                                                                if (!res.ok) throw new Error(backendData.message || "Failed to post");

                                                                                                                                                                                                                                                                      setMsg("✅ Property added successfully!");
                                                                                                                                                                                                                                                                            refresh();
                                                                                                                                                                                                                                                                                  setTitle("");
                                                                                                                                                                                                                                                                                        setPrice("");
                                                                                                                                                                                                                                                                                              setLocation("");
                                                                                                                                                                                                                                                                                                    setContact("");
                                                                                                                                                                                                                                                                                                          setImage(null);
                                                                                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                                                                                    console.error(err);
                                                                                                                                                                                                                                                                                                                          setMsg(`❌ ${err.message}`);
                                                                                                                                                                                                                                                                                                                              } finally {
                                                                                                                                                                                                                                                                                                                                    setLoading(false);
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                <div className="add-property">
                                                                                                                                                                                                                                                                                                                                                      <h3>Add New Apartment</h3>
                                                                                                                                                                                                                                                                                                                                                            {msg && <p>{msg}</p>}

                                                                                                                                                                                                                                                                                                                                                                  <form onSubmit={handleUpload}>
                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                    type="text"
                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Apartment Title"
                                                                                                                                                                                                                                                                                                                                                                                                        value={title}
                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setTitle(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Price (₦)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPrice(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Location"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={location}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setLocation(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Contact Info"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={contact}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setContact(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      accept="image/*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setImage(e.target.files[0])}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? "Uploading..." : "Post Apartment"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default AddProperty;