import { useState } from "react";

function AddProperty({ user, onAdded }) {
  const [title, setTitle] = useState("");
    const [price, setPrice] = useState("");
      const [location, setLocation] = useState("");
        const [description, setDescription] = useState("");
          const [image, setImage] = useState(null);
            const [loading, setLoading] = useState(false);
              const [error, setError] = useState("");

                const handleSubmit = async (e) => {
                    e.preventDefault();
                        setError("");
                            setLoading(true);

                                try {
                                      // Cloudinary upload first
                                            const formData = new FormData();
                                                  formData.append("file", image);
                                                        formData.append("upload_preset", "homdira_uploads"); // your upload preset in Cloudinary

                                                              const uploadRes = await fetch(
                                                                      `https://api.cloudinary.com/v1_1/dwwbua1jx/image/upload`,
                                                                              {
                                                                                        method: "POST",
                                                                                                  body: formData,
                                                                                                          }
                                                                                                                );

                                                                                                                      const uploadData = await uploadRes.json();
                                                                                                                            const imageUrl = uploadData.secure_url;

                                                                                                                                  // Now send to backend
                                                                                                                                        const token = localStorage.getItem("token");
                                                                                                                                              const res = await fetch(`https://homdira-backend.onrender.com/api/properties`, {
                                                                                                                                                      method: "POST",
                                                                                                                                                              headers: {
                                                                                                                                                                        "Content-Type": "application/json",
                                                                                                                                                                                  Authorization: `Bearer ${token}`,
                                                                                                                                                                                          },
                                                                                                                                                                                                  body: JSON.stringify({
                                                                                                                                                                                                            title,
                                                                                                                                                                                                                      price,
                                                                                                                                                                                                                                location,
                                                                                                                                                                                                                                          description,
                                                                                                                                                                                                                                                    image: imageUrl,
                                                                                                                                                                                                                                                            }),
                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                        const data = await res.json();

                                                                                                                                                                                                                                                                              if (res.ok) {
                                                                                                                                                                                                                                                                                      onAdded(); // Refresh property list after successful addition
                                                                                                                                                                                                                                                                                              setTitle("");
                                                                                                                                                                                                                                                                                                      setPrice("");
                                                                                                                                                                                                                                                                                                              setLocation("");
                                                                                                                                                                                                                                                                                                                      setDescription("");
                                                                                                                                                                                                                                                                                                                              setImage(null);
                                                                                                                                                                                                                                                                                                                                      alert("🏡 Property added successfully!");
                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                    setError(data.message || "Something went wrong");
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                    console.error(err);
                                                                                                                                                                                                                                                                                                                                                                          setError("Error uploading property. Please try again.");
                                                                                                                                                                                                                                                                                                                                                                              } finally {
                                                                                                                                                                                                                                                                                                                                                                                    setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                <div className="add-property">
                                                                                                                                                                                                                                                                                                                                                                                                      <h3>Add New Apartment</h3>
                                                                                                                                                                                                                                                                                                                                                                                                            {error && <p className="error">{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                  <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                                    type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Apartment Title"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setTitle(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Price (₦)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPrice(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Location (e.g., Lekki, Lagos)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={location}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setLocation(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Description (e.g., 2-bedroom, well-furnished)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setDescription(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rows={3}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      accept="image/*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setImage(e.target.files[0])}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? "Uploading..." : "Add Apartment"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default AddProperty;