import React, { useEffect, useState } from "react";
import axios from "axios";

const MyApartments = ({ user }) => {
  const [apartments, setApartments] = useState([]);

    useEffect(() => {
        const fetchMyApartments = async () => {
              try {
                      const res = await axios.get(`${import.meta.env.VITE_API_URL}/api/properties/landlord/${user._id}`);
                              setApartments(res.data);
                                    } catch (error) {
                                            console.error("Error fetching apartments", error);
                                                  }
                                                      };
                                                          if (user) fetchMyApartments();
                                                            }, [user]);

                                                              return (
                                                                  <div className="my-apartments-container">
                                                                        <style>{`
                                                                                .my-apartments-container {
                                                                                          padding: 20px;
                                                                                                    background-color: #f9fdf9;
                                                                                                              min-height: 100vh;
                                                                                                                        text-align: center;
                                                                                                                                }
                                                                                                                                        .my-apartments-container h2 {
                                                                                                                                                  color: #0a9d57;
                                                                                                                                                            margin-bottom: 15px;
                                                                                                                                                                      font-weight: 700;
                                                                                                                                                                              }
                                                                                                                                                                                      .apartment-card {
                                                                                                                                                                                                background: #fff;
                                                                                                                                                                                                          border-radius: 10px;
                                                                                                                                                                                                                    box-shadow: 0 3px 10px rgba(0,0,0,0.1);
                                                                                                                                                                                                                              padding: 15px;
                                                                                                                                                                                                                                        margin: 10px auto;
                                                                                                                                                                                                                                                  max-width: 400px;
                                                                                                                                                                                                                                                            text-align: left;
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                            .apartment-card img {
                                                                                                                                                                                                                                                                                      width: 100%;
                                                                                                                                                                                                                                                                                                border-radius: 8px;
                                                                                                                                                                                                                                                                                                          height: 200px;
                                                                                                                                                                                                                                                                                                                    object-fit: cover;
                                                                                                                                                                                                                                                                                                                              margin-bottom: 10px;
                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                              .apartment-card h3 {
                                                                                                                                                                                                                                                                                                                                                        color: #0a9d57;
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                        .apartment-card p {
                                                                                                                                                                                                                                                                                                                                                                                  color: #333;
                                                                                                                                                                                                                                                                                                                                                                                            margin: 5px 0;
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                          `}</style>

                                                                                                                                                                                                                                                                                                                                                                                                                <h2>My Apartments</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                      {apartments.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                              <p>No apartments added yet.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                            apartments.map((apt) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={apt._id} className="apartment-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img src={apt.image} alt={apt.title} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>{apt.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>📍 {apt.location}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>💰 ₦{apt.price}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default MyApartments;