import React from "react";
import Navbar from "../components/Navbar";
import { usePaystackPayment } from "react-paystack";

function Premium() {
  const publicKey = "pk_test_7a444f5742c8909630e45db04f6a94e22f19ece3"; // Your Paystack public key

    const config = {
        reference: new Date().getTime().toString(),
            email: "landlord@homdira.com", // You can replace this with logged-in user’s email
                amount: 300000, // ₦3000 (Paystack uses kobo, so multiply by 100)
                    publicKey,
                      };

                        const onSuccess = (reference) => {
                            alert("Payment Successful! Reference: " + reference.reference);
                              };

                                const onClose = () => {
                                    alert("Payment closed!");
                                      };

                                        const initializePayment = usePaystackPayment(config);

                                          return (
                                              <div className="home-page">
                                                    <Navbar />
                                                          <div
                                                                  style={{
                                                                            background: "#ffffff",
                                                                                      padding: "30px",
                                                                                                borderRadius: "10px",
                                                                                                          boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
                                                                                                                    maxWidth: "600px",
                                                                                                                              margin: "40px auto",
                                                                                                                                        textAlign: "center",
                                                                                                                                                }}
                                                                                                                                                      >
                                                                                                                                                              <h2 style={{ color: "#2e8b57", marginBottom: "10px" }}>Homdira Premium 💎</h2>
                                                                                                                                                                      <p style={{ color: "#444", marginBottom: "25px" }}>
                                                                                                                                                                                Unlock powerful features designed to give landlords more visibility
                                                                                                                                                                                          and tenants more trust. Choose our affordable premium package.
                                                                                                                                                                                                  </p>

                                                                                                                                                                                                          <div
                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                background: "#f8fff9",
                                                                                                                                                                                                                                            border: "1px solid #d9f2e0",
                                                                                                                                                                                                                                                        padding: "20px",
                                                                                                                                                                                                                                                                    borderRadius: "8px",
                                                                                                                                                                                                                                                                                marginBottom: "25px",
                                                                                                                                                                                                                                                                                            textAlign: "left",
                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                        <h3 style={{ color: "#2e8b57" }}>✨ Premium Benefits:</h3>
                                                                                                                                                                                                                                                                                                                                  <ul style={{ marginTop: "10px", lineHeight: "1.8", color: "#333" }}>
                                                                                                                                                                                                                                                                                                                                              <li>✅ Unlimited Property Postings</li>
                                                                                                                                                                                                                                                                                                                                                          <li>✅ Featured Listing (More Views)</li>
                                                                                                                                                                                                                                                                                                                                                                      <li>✅ Priority in Search Results</li>
                                                                                                                                                                                                                                                                                                                                                                                  <li>✅ Direct Chat Support</li>
                                                                                                                                                                                                                                                                                                                                                                                              <li>✅ Trusted “Verified Landlord” Badge</li>
                                                                                                                                                                                                                                                                                                                                                                                                        </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => initializePayment(onSuccess, onClose)}
                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: "#2e8b57",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "14px 25px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            💎 Upgrade Now for ₦3,000
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Premium;