import { useState } from "react";

function Register({ setPage }) {
  const [name, setName] = useState("");
    const [email, setEmail] = useState("");
      const [password, setPassword] = useState("");
        const [phone, setPhone] = useState("");
          const [role, setRole] = useState("tenant");
            const [loading, setLoading] = useState(false);
              const [msg, setMsg] = useState("");

                const handleRegister = async (e) => {
                    e.preventDefault();
                        setLoading(true);
                            setMsg("");

                                try {
                                      const res = await fetch("https://homdira-backend.onrender.com/api/auth/register", {
                                              method: "POST",
                                                      headers: { "Content-Type": "application/json" },
                                                              body: JSON.stringify({ name, email, password, phone, role }),
                                                                    });

                                                                          const data = await res.json();
                                                                                if (!res.ok) throw new Error(data.message || "Registration failed");

                                                                                      setMsg("✅ Registration successful! Please log in.");
                                                                                            setTimeout(() => setPage("login"), 1500);
                                                                                                } catch (err) {
                                                                                                      setMsg(`❌ ${err.message}`);
                                                                                                          } finally {
                                                                                                                setLoading(false);
                                                                                                                    }
                                                                                                                      };

                                                                                                                        return (
                                                                                                                            <div className="auth-container">
                                                                                                                                  <h2>Register</h2>
                                                                                                                                        {msg && <p>{msg}</p>}

                                                                                                                                              <form onSubmit={handleRegister}>
                                                                                                                                                      <input
                                                                                                                                                                type="text"
                                                                                                                                                                          placeholder="Full Name"
                                                                                                                                                                                    value={name}
                                                                                                                                                                                              onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                                        required
                                                                                                                                                                                                                />

                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                  type="email"
                                                                                                                                                                                                                                            placeholder="Email"
                                                                                                                                                                                                                                                      value={email}
                                                                                                                                                                                                                                                                onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                              placeholder="Password"
                                                                                                                                                                                                                                                                                                                        value={password}
                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                      type="tel"
                                                                                                                                                                                                                                                                                                                                                                                placeholder="Phone"
                                                                                                                                                                                                                                                                                                                                                                                          value={phone}
                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPhone(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                              <select value={role} onChange={(e) => setRole(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="tenant">Tenant</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="landlord">Landlord</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="submit" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? "Registering..." : "Register"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Already have an account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span onClick={() => setPage("login")} className="link">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Login here
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default Register;