import React, { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import "./Auth.css";

function Register() {
  const navigate = useNavigate();
    const [form, setForm] = useState({
        name: "",
            email: "",
                password: "",
                    role: "tenant",
                      });

                        const handleChange = (e) => {
                            setForm({ ...form, [e.target.name]: e.target.value });
                              };

                                const handleSubmit = async (e) => {
                                    e.preventDefault();

                                        const res = await fetch("https://homdira-backend.onrender.com/api/auth/register", {
                                              method: "POST",
                                                    headers: { "Content-Type": "application/json" },
                                                          body: JSON.stringify(form),
                                                              });

                                                                  const data = await res.json();

                                                                      if (res.ok) {
                                                                            alert("Registration successful!");
                                                                                  navigate("/login");
                                                                                      } else {
                                                                                            alert(data.message || "Registration failed");
                                                                                                }
                                                                                                  };

                                                                                                    return (
                                                                                                        <div className="auth-container">
                                                                                                              <div className="auth-box">
                                                                                                                      <h2 className="auth-title">Create an Account 🏡</h2>
                                                                                                                              <p className="auth-subtitle">Join Homdira today!</p>

                                                                                                                                      <form onSubmit={handleSubmit}>
                                                                                                                                                <input
                                                                                                                                                            type="text"
                                                                                                                                                                        name="name"
                                                                                                                                                                                    placeholder="Full Name"
                                                                                                                                                                                                value={form.name}
                                                                                                                                                                                                            onChange={handleChange}
                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                        type="email"
                                                                                                                                                                                                                                                                    name="email"
                                                                                                                                                                                                                                                                                placeholder="Email Address"
                                                                                                                                                                                                                                                                                            value={form.email}
                                                                                                                                                                                                                                                                                                        onChange={handleChange}
                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                                                                                name="password"
                                                                                                                                                                                                                                                                                                                                                                            placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                        value={form.password}
                                                                                                                                                                                                                                                                                                                                                                                                    onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                    <select name="role" value={form.role} onChange={handleChange}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="tenant">Tenant</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="landlord">Landlord</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" className="auth-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Register
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="auth-footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Already have an account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link to="/login" className="auth-link">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Login
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default Register;