import React, { useState } from "react";

function AddProperty({ user, onAdded }) {
  const [form, setForm] = useState({
      title: "",
          location: "",
              price: "",
                  description: "",
                      contact: "",
                          image: null,
                            });
                              const [loading, setLoading] = useState(false);

                                const handleChange = (e) => {
                                    const { name, value, files } = e.target;
                                        setForm({ ...form, [name]: files ? files[0] : value });
                                          };

                                            const handleSubmit = async (e) => {
                                                e.preventDefault();
                                                    setLoading(true);
                                                        try {
                                                              const data = new FormData();
                                                                    Object.keys(form).forEach((key) => {
                                                                            data.append(key, form[key]);
                                                                                  });
                                                                                        data.append("landlordId", user._id);

                                                                                              const res = await fetch("https://homdira-backend.onrender.com/api/properties", {
                                                                                                      method: "POST",
                                                                                                              body: data,
                                                                                                                    });

                                                                                                                          if (res.ok) {
                                                                                                                                  alert("Property added successfully!");
                                                                                                                                          setForm({
                                                                                                                                                    title: "",
                                                                                                                                                              location: "",
                                                                                                                                                                        price: "",
                                                                                                                                                                                  description: "",
                                                                                                                                                                                            contact: "",
                                                                                                                                                                                                      image: null,
                                                                                                                                                                                                              });
                                                                                                                                                                                                                      onAdded();
                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                    alert("Failed to add property.");
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                    console.error(err);
                                                                                                                                                                                                                                                          alert("Something went wrong.");
                                                                                                                                                                                                                                                              } finally {
                                                                                                                                                                                                                                                                    setLoading(false);
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                <div className="add-property-container">
                                                                                                                                                                                                                                                                                      <h2>Add Apartment 🏠</h2>
                                                                                                                                                                                                                                                                                            <form className="add-form" onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                        name="title"
                                                                                                                                                                                                                                                                                                                                  placeholder="Apartment title (e.g., 2 Bedroom Flat)"
                                                                                                                                                                                                                                                                                                                                            value={form.title}
                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                          type="text"
                                                                                                                                                                                                                                                                                                                                                                                                    name="location"
                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Location (e.g., Lekki, Lagos)"
                                                                                                                                                                                                                                                                                                                                                                                                                        value={form.location}
                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name="price"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Price (₦)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={form.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name="description"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Short description"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rows="3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={form.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name="contact"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Contact number or email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={form.contact}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="file" name="image" accept="image/*" onChange={handleChange} required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? "Uploading..." : "Post Apartment"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default AddProperty;