import React, { useState } from "react";
import axios from "axios";

const AddProperty = ({ user, onSuccess }) => {
  const [form, setForm] = useState({
      title: "",
          location: "",
              price: "",
                  image: "",
                    });
                      const [loading, setLoading] = useState(false);
                        const [message, setMessage] = useState("");

                          const handleChange = (e) => {
                              setForm({ ...form, [e.target.name]: e.target.value });
                                };

                                  const handleSubmit = async (e) => {
                                      e.preventDefault();
                                          if (!user) {
                                                setMessage("Please log in to post an apartment.");
                                                      return;
                                                          }

                                                              try {
                                                                    setLoading(true);
                                                                          const res = await axios.post(
                                                                                  `${import.meta.env.VITE_API_URL}/api/properties`,
                                                                                          { ...form, landlord: user._id },
                                                                                                  { headers: { "Content-Type": "application/json" } }
                                                                                                        );
                                                                                                              setLoading(false);
                                                                                                                    setMessage("Property added successfully!");
                                                                                                                          setForm({ title: "", location: "", price: "", image: "" });
                                                                                                                                if (onSuccess) onSuccess(res.data);
                                                                                                                                    } catch (err) {
                                                                                                                                          setLoading(false);
                                                                                                                                                setMessage("Failed to add property. Try again.");
                                                                                                                                                    }
                                                                                                                                                      };

                                                                                                                                                        return (
                                                                                                                                                            <div className="add-property-container">
                                                                                                                                                                  <style>{`
                                                                                                                                                                          .add-property-container {
                                                                                                                                                                                    max-width: 500px;
                                                                                                                                                                                              margin: 40px auto;
                                                                                                                                                                                                        background: #ffffff;
                                                                                                                                                                                                                  border-radius: 10px;
                                                                                                                                                                                                                            padding: 25px;
                                                                                                                                                                                                                                      box-shadow: 0 4px 12px rgba(10, 157, 87, 0.15);
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                      .add-property-container h2 {
                                                                                                                                                                                                                                                                text-align: center;
                                                                                                                                                                                                                                                                          color: #0a9d57;
                                                                                                                                                                                                                                                                                    margin-bottom: 20px;
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                    .add-property-form {
                                                                                                                                                                                                                                                                                                              display: flex;
                                                                                                                                                                                                                                                                                                                        flex-direction: column;
                                                                                                                                                                                                                                                                                                                                  gap: 15px;
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                  .add-property-form input {
                                                                                                                                                                                                                                                                                                                                                            padding: 12px;
                                                                                                                                                                                                                                                                                                                                                                      border: 1px solid #cfcfcf;
                                                                                                                                                                                                                                                                                                                                                                                border-radius: 8px;
                                                                                                                                                                                                                                                                                                                                                                                          font-size: 16px;
                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                          .add-property-form button {
                                                                                                                                                                                                                                                                                                                                                                                                                    background: #0a9d57;
                                                                                                                                                                                                                                                                                                                                                                                                                              color: white;
                                                                                                                                                                                                                                                                                                                                                                                                                                        font-size: 17px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  font-weight: 600;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: 12px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border-radius: 8px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: pointer;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transition: 0.3s;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .add-property-form button:hover {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: #087c44;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .message {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        margin-top: 15px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  text-align: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: #0a9d57;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      font-weight: 600;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `}</style>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>Add New Apartment</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <form onSubmit={handleSubmit} className="add-property-form">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name="title"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Apartment Title"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={form.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name="location"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Location"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={form.location}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name="price"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Price (₦)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={form.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name="image"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Image URL"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={form.image}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? "Posting..." : "Post Apartment"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {message && <p className="message">{message}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default AddProperty;